namespace scp.filestorage.Data.Models
{
    /// <summary>
    /// Defines supported two-factor authentication method types.
    /// </summary>
    public enum TwoFactorMethodType
    {
        /// <summary>
        /// No two-factor authentication method is selected.
        /// </summary>
        None = 0,

        /// <summary>
        /// Time-based one-time password generated by an authenticator application.
        /// </summary>
        AuthenticatorApp = 1,

        /// <summary>
        /// One-time code delivered by email.
        /// </summary>
        Email = 2,

        /// <summary>
        /// One-time code delivered by SMS.
        /// </summary>
        Sms = 3
    }

    /// <summary>
    /// Defines the status of a two-factor authentication challenge.
    /// </summary>
    public enum TwoFactorChallengeStatus
    {
        /// <summary>
        /// Challenge is active and can still be verified.
        /// </summary>
        Pending = 0,

        /// <summary>
        /// Challenge was successfully verified.
        /// </summary>
        Verified = 1,

        /// <summary>
        /// Challenge expired before verification.
        /// </summary>
        Expired = 2,

        /// <summary>
        /// Challenge was cancelled or invalidated.
        /// </summary>
        Cancelled = 3,

        /// <summary>
        /// Challenge was blocked because too many failed attempts were made.
        /// </summary>
        Blocked = 4
    }
}
