using scp.filestorage.Data.Models;

namespace scp.filestorage.Services.Auth
{
    public sealed class LoginRequest
    {
        /// <summary>
        /// User name or email entered by the user.
        /// </summary>
        public string Login { get; init; } = string.Empty;

        /// <summary>
        /// Plain text password entered by the user.
        /// </summary>
        public string Password { get; init; } = string.Empty;

        /// <summary>
        /// Optional TOTP code from an authenticator application.
        /// When provided, authenticator-based two-factor verification can be completed in the same login request.
        /// </summary>
        public string? TwoFactorCode { get; init; }

        /// <summary>
        /// IP address of the client.
        /// </summary>
        public string? IpAddress { get; init; }

        /// <summary>
        /// User agent of the client.
        /// </summary>
        public string? UserAgent { get; init; }

        /// <summary>
        /// Remember the user on this device. When true, the authentication cookie will have a longer expiration time.
        /// </summary>
        public bool Remember { get; init; }
    }

    /// <summary>
    /// Result of password authentication.
    /// </summary>
    public sealed class LoginResult
    {
        public AuthLoginStatus Status { get; init; }

        public Guid? UserId { get; init; }

        public string UserName { get; init; } = string.Empty;

        public bool RequiresTwoFactor { get; init; }

        public TwoFactorMethodType TwoFactorMethod { get; init; }

        /// <summary>
        /// Plain challenge token returned to the client.
        /// Only the hash of this token is stored in the database.
        /// </summary>
        public string? ChallengeToken { get; init; }

        public DateTime? ChallengeExpiresUtc { get; init; }

        public IReadOnlyList<string> Roles { get; init; } = Array.Empty<string>();

        public bool Succeeded => Status == AuthLoginStatus.Success;
    }

    /// <summary>
    /// Request used to verify a two-factor authentication code.
    /// </summary>
    public sealed class VerifyTwoFactorRequest
    {
        /// <summary>
        /// Plain challenge token previously returned by LoginAsync.
        /// </summary>
        public string ChallengeToken { get; init; } = string.Empty;

        /// <summary>
        /// Two-factor verification code entered by the user.
        /// </summary>
        public string Code { get; init; } = string.Empty;

        /// <summary>
        /// IP address of the client.
        /// </summary>
        public string? IpAddress { get; init; }

        /// <summary>
        /// User agent of the client.
        /// </summary>
        public string? UserAgent { get; init; }
    }

    /// <summary>
    /// Result of two-factor authentication verification.
    /// </summary>
    public sealed class VerifyTwoFactorResult
    {
        public TwoFactorVerifyStatus Status { get; init; }

        public Guid? UserId { get; init; }

        public string UserName { get; init; } = string.Empty;

        public IReadOnlyList<string> Roles { get; init; } = Array.Empty<string>();

        public bool Succeeded => Status == TwoFactorVerifyStatus.Success;
    }

    /// <summary>
    /// Result of authenticator application setup.
    /// </summary>
    public sealed class AuthenticatorSetupResult
    {
        public TwoFactorSetupStatus Status { get; init; }

        /// <summary>
        /// Plain TOTP secret. Show it to the user only during setup.
        /// Store only encrypted secret in the database.
        /// </summary>
        public string? Secret { get; init; }

        /// <summary>
        /// otpauth:// URI for QR code generation.
        /// </summary>
        public string? OtpAuthUri { get; init; }

        /// <summary>
        /// Base64 encoded PNG QR code.
        /// </summary>
        public string QrCodePngBase64 { get; init; } = string.Empty;
    }

    /// <summary>
    /// Request used to confirm authenticator application setup.
    /// </summary>
    public sealed class ConfirmAuthenticatorSetupRequest
    {
        /// <summary>
        /// TOTP code generated by the authenticator application.
        /// </summary>
        public string Code { get; init; } = string.Empty;
    }
}
